# -*- coding: utf-8 -*-
"""pratica01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mO85_F3LC58l7PrBiH6X3prw_b_wUI4p
"""

nome = "Katie"
idade = "20"
gosto_de = "ler"

print(f"Meu nome é {nome}.")
print(f"Eu gosto de {gosto_de}")
print(f"Eu tenho {idade}")
print(f"{nome} gosta de {gosto_de} e tem {idade}.")